language: swift
os: ios
osx_image: xcode9.3
xcode_project: QuickPlayer/QuickPlayer.xcodeproj 
xcode_scheme: QuickPlayer

script:
- xcodebuild clean build test -workspace QuickPlayer-Example.xcworkspace -scheme QuickPlayer -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES

