language: objective-c
os: osx
osx_image: xcode8.3
xcode_project: QuickPlayer/QuickPlayer.xcodeproj 
xcode_scheme: QuickPlayer
xcode_sdk: iphonesimulator8.3

script:
- xcodebuild clean build test -project QuickPlayer/QuickPlayer.xcodeproj -scheme QuickPlayer

