language: swift
os: ios
osx_image: xcode9.3
xcode_project: QuickPlayer/QuickPlayer.xcodeproj 
xcode_scheme: QuickPlayer

script:
- xcodebuild clean test -workspace QuickPlayer-Example.xcworkspace -scheme QuickPlayer -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' -enableCodeCoverage YES | xcpretty
